### ISSUE TITLE
Title page issues

### ISSUE THREAD

**Issue by LvLIshay** [Vegan-info/vegan-info.github.io#19]
![35C3E03A-C5BC-4B28-9FE6-FAAF9179EA69](https://user-images.githubusercontent.com/125837606/219982539-65252dfb-52d1-49bd-9eff-94a24afeb8b6.jpeg)

The word billions should be trillions and I think an exclamation point would go well after “join us to help change the lives of animals.”

**Comment by devktor** [comment]
fixed
