### ISSUE TITLE
Space and dash errors

### ISSUE THREAD

**Issue by LvLIshay** [Vegan-info/vegan-info.github.io#27]
![45BD72FF-FC40-4A69-813F-5FCCB14773BF](https://user-images.githubusercontent.com/125837606/219983391-932bb32e-39b0-4d35-a339-9d262b7945e6.jpeg)
 
 every day should be everyday… and animal based should be animal-based, similar to plant-based.

**Comment by LvLIshay** [comment]
Also it’s should be “it is” to avoid contraction.

**Comment by devktor** [comment]
fixed
