### ISSUE TITLE
Plant-based?

### ISSUE THREAD

**Issue by LvLIshay** [Vegan-info/vegan-info.github.io#28]
![2DF9C841-1054-4FDB-A5C1-415540F17BA7](https://user-images.githubusercontent.com/125837606/219983468-2fb74ed0-9efa-4d4a-b926-7cbac3fd36cc.jpeg)

This part is a little odd seeing as the website is meant to cover going vegan, not plant-based. Maybe remove all together? Not sure

**Comment by devktor** [comment]
fixed
