### ISSUE TITLE
Grammatical issues

### ISSUE THREAD

**Issue by ellevgn** [Vegan-info/vegan-info.github.io#4]
![thdrhee](https://user-images.githubusercontent.com/125830533/219973630-5dd9d9ce-e949-436c-ad2c-15affc79c54f.PNG)

Three items circled, corrections numbered: 

1) ourselves: What (colon isn't currently present)
2)  without (rather than with out) 
3) below), (switch the comma around)

**Comment by devktor** [comment]
fixed
